accounts/urls.py
from django.conf.urls import url
from .import views


app_name= 'accounts'

urlpatterns = [
	url(r'^$', views.base,name='base'),
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
  
]

todo/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls import  url,include
from todolist import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('',include('accounts.urls')),
    url(r'^todo/', include('todolist.urls')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todolist/urls.py
from django.contrib import admin
from django.conf.urls import  url
from .import views
app_name='todolist'
urlpatterns = [
    #url('admin/', admin.site.urls),
    url(r'^$', views.home,name='home'),
    url(r'^mark/(?P<pk>\d+)$',views.mark ,name="complete"),
    url(r'^unmark/(?P<pk>\d+)$',views.unmark ,name="incomplete"),
    url(r'^see/(?P<pk>\d+)$',views.see,name="see"),
    url(r'^deletecompleted/$',views.deletecompleted,name="deletecompleted"),
    url(r'^delete/(?P<pk>\d+)$',views.delete,name="delete"),
    url(r'^update/(?P<pk>\d+)$',views.update,name="update"),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,UserManager

class CustomUserManager(UserManager):
    pass

# Create your models here.
class CustomUser(AbstractUser):
	email=models.EmailField(unique=True)
	
	USERNAME_FIELD='email'
	REQUIRED_FIELDS=['username']

	object=CustomUserManager()
  
	def __str__(self):
  		return self.username

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.
class Todo(models.Model):
    content = models.TextField()
    time=models.TimeField(default=timezone.now(),null=True)
    date = models.DateField(default=datetime.now(),null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    mark = models.BooleanField(default=False)

    def __str__(self):
        return self.content

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User

from .models import CustomUser
from django.contrib.auth import get_user_model
User = get_user_model()

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields


class UserLoginForm(forms.Form):
    username = forms.CharField(label ="")
    password = forms.CharField(label="",widget=forms.PasswordInput)



class UserSignUpForm(CustomUserCreationForm):
    full_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254 )
   

    class Meta:
        model = User
        fields = ('full_name','username' , 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserSignUpForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

todolist/forms.py
from django import forms
from .models import *

class TodoForm(forms.ModelForm):
	content = forms.CharField(label="Todo",widget=forms.Textarea(attrs={'class': '','placeholder':'Enter todo list item','rows':'1',})) 
	
	class Meta:
 		model = Todo
 		fields = ['content','date','time']

 

accounts/views.py
from django.contrib import messages

from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from .forms import UserLoginForm,UserSignUpForm
from django.http import HttpResponseRedirect,HttpResponse

from django.urls import reverse
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.
def base(request):
    return render(request,'accounts/base.html')
def signup_view(request):
    if request.method =='POST':
        form=UserSignUpForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.is_active=True
            user.save()
            login(request,user)
            return redirect('todolist:home')
    else:
        form=UserSignUpForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method =='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('todolist:home')
    else:
        form= AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})
def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('accounts:base')

todolist/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse ,JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.conf import settings
from django.core.mail import send_mail
from django.utils import timezone
import datetime
from django.contrib.auth import get_user_model
User=get_user_model()

from django.contrib.auth.decorators import login_required
@login_required
def home(request):

    list=Todo.objects.all().order_by('-id').filter(user=request.user)
    form = TodoForm()


    if request.method=="POST":
        form=TodoForm(request.POST or None)
        if form.is_valid():
            u=form.save(commit=False)
            u.user=request.user
            print(u.user)

            u.save()
            form=TodoForm()
    todos=Todo.objects.all().filter(mark__exact=True).filter(user=request.user)
    now=datetime.datetime.now().strftime('%H:%M')
    print(now)
    for todo in list:
        l=(todo.time.strftime('%H:%M'))
        print(l)
        content=str(todo.content)
        u=str(todo.user.email)
        if now==l:
            send_mail('todo alert mail',content,'genitish@gmail.com',[u])

    return render(request,'todolist/index.html',{'list':list,'form':form,'todos':todos})
@login_required
def see(request,pk):
    list=Todo.objects.filter(pk=pk)

    return render(request,'todolist/schedule.html',{'list':list})
@login_required
def mark(request,pk):
    todo=Todo.objects.get(pk=pk)
    todo.mark=True
    todo.save()
    return redirect('todolist:home')
@login_required
def unmark(request,pk):
    todo=Todo.objects.get(pk=pk)
    todo.mark=False
    todo.save()
    return redirect('todolist:home')
@login_required
def deletecompleted(request):
    Todo.objects.filter(mark__exact=True).delete()

    return redirect('todolist:home')
@login_required
def delete(request,pk):

    todo=Todo.objects.get(pk=pk)
    todo.delete()

    return redirect('todolist:home')
@login_required
def update(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
    form = TodoForm()
    if request.method=="POST":
        form=TodoForm(request.POST or None,instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todolist:home')
    return render(request,'todolist/update.html',{'form':form})

accounts/templates/accounts/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>TodoList App</title>
  <meta http-equiv="refresh" content="45">
  <!-- bootstrap cdn -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<style>
    body{
        background-image: url("{% static 'img/chicago-wallpaper-3.jpg' %}");

  }
  </style>
</head>

<body>
  <div class="hero">
    <div class="container">
    <br>
    <br><br><br>
      <h3 class="display-2 text-center">TodoList</h3>
      <p class="lead text-center">Welcome to my todoList applications</p>

      <div class="row">

<br>
<br>
<br>
       <div class=" col-lg-9">


     <a href="{% url 'accounts:login'  %}"> <button  class = "btn btn-primary " type="submit" name="login" style="font-size: 30px; margin-right: 115px;">Login</button></a>

   <a href="{% url 'accounts:signup' %}"> <button  class = "btn btn-danger " type="submit" name="signup" style="font-size: 30px; margin-right: 20px;">Signup</button></a>


        </div>
      </div>
    </div>
</div>
  </body>
</html>

accounts/templates/accounts/login.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>TodoList App</title>
  <meta http-equiv="refresh" content="45">
  <!-- bootstrap cdn -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <style>
  body{
      background-image: url("{% static 'img/chicago-wallpaper-3.jpg' %}");

}
</style>

</head>

<body>
  <div class="hero">
    <div class="container">

 <div class="parallax-signup" data-parallax="scroll" data-z-index="1" data-image-src="/static/2.jpg">
    <br><br><br>
    <h1 class = "para-signup" align = "center">LOG IN</h1>
    <form class="site-form-signup" action="{% url 'accounts:login'%}" method="post">
      {%csrf_token%}
      {{form}}
      {% if request.GET.next %}
        <input type="hidden"name="next"value="{{request.GET.next}}">
      {% endif %}
      <input type="submit"value="Login">
    </form>
  </div>
  </div>
</div>
</body>
</html>

accounts/templates/accounts/signup.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>TodoList App</title>
  <meta http-equiv="refresh" content="45">
  <!-- bootstrap cdn -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

  <style>
  body{
      background-image: url("{% static 'img/chicago-wallpaper-3.jpg' %}");

}
</style>
</head>

<body>
  <div class="hero">
    <div class="container">


    <br>
    <br>
    <h1 class="para-signup" align = "center">SIGN UP</h1>
    <form class="site-form-signup"  method="post">
        {% csrf_token %}
      {{form}}
      <input type="submit"value="signup">
    </form>
  </div>
</div>

  </body>
  </html>

todolist/templates/todolist/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>TodoList App</title>
	<meta http-equiv="refresh" content="45">
	<!-- bootstrap cdn -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- google fonts -->
	<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<style>
  body{
      background-image: url("{% static 'img/chicago-wallpaper-3.jpg' %}");

}
</style>
</head>

<body>
	<div class="hero">
		<div class="container">
			<ul class="logout" style="list-type:none;" >
			<h3 class="user">	<li>Hello {{request.user.email}}</li>
		<li>	<form   class="logout"  action ="{% url 'accounts:logout' %}" method="post">
							 {% csrf_token %}
							 <button type ="submit" class="btn btn-primary">Logout</button>
		</form></li></h3>
</ul>
			<h3 class="display-2 text-center">TodoList</h3>
			<p class="lead text-center">Welcome to my todoList applications</p>
			<br>
			<br>
			<div class="row">
				<form id="form" class="col-lg-6 col-8 mx-auto" method="post">
					<div class="input-group">
						{% csrf_token %}
						{{form.as_p}}

						<span>
							<button id="btn" type="submit" class="btn btn-primary " style="font-size: 20px;">Submit</button>
						</span>
					</div>
				</form>
			</div>

			<br>
			<div class="row">


				<ul id="list" class="list col-lg-6 col-8 mx-auto">
					<h3>List of Todo's</h3>
					<br>
					<br>
					<!-- <li>this is a todo item <input type="checkbox" class="checkbox"></li>
					<li>this is a todo item <input type="checkbox" class="checkbox"></li> -->
					{% for l in list %}

  					<li>{{l.content}}
  					<a href="{% url 'todolist:update' l.pk %}"> <button  class = "btn btn-primary " type="submit" name="update" >Update</button></a>

   <a href="{% url 'todolist:delete' l.pk %}"> <button  class = "btn btn-primary " type="submit" name="delete" >Delete</button></a>


 	{% if l.mark %}

 		<a href="{% url 'todolist:incomplete' l.pk %}"><button  class = "btn btn-primary " type="submit" name="mark" >Unmark</button></a>

 	{% else %}
 		<a href="{% url 'todolist:complete' l.pk %}"><button  class = "btn btn-primary " type="submit" name="mark" >Mark</button></a>
 	{% endif %}
 	<a href="{% url 'todolist:see' l.pk %}"><button  class = "btn btn-primary " type="submit" name="mark" >Schedule</button></a>
 	</li>



  <br>
{% endfor %}
				<a href="{% url 'todolist:deletecompleted' %}"> <button type="submit" class = "btn btn-danger " name="deletecompleted" style="font-size: 18px;">Delete Marked</button></a>
			</ul>
			</div>

				<div class="row">


				<ul id="marklist" class="list col-lg-6 col-8 mx-auto">
					<h3>List of  mark Todo's</h3>
					<br>
					<br>
					<!-- <li>this is a todo item <input type="checkbox" class="checkbox"></li>
					<li>this is a todo item <input type="checkbox" class="checkbox"></li> -->
					{% for t in todos %}

  					<li>{{t.content}}
  					<a href="{% url 'todolist:update' t.pk %}"> <button  class = "btn btn-primary " type="submit" name="update" >Update</button></a>

   <a href="{% url 'todolist:delete' t.pk %}"> <button  class = "btn btn-primary " type="submit" name="delete" >Delete</button></a>


 	{% if t.mark %}

 		<a href="{% url 'todolist:incomplete' t.pk %}"><button  class = "btn btn-primary " type="submit" name="mark" >Unmark</button></a>

 	{% else %}
 		<a href="{% url 'todolist:complete' t.pk %}"><button  class = "btn btn-primary " type="submit" name="mark" >Mark</button></a>
 	{% endif %}
 	<a href="{% url 'todolist:see' t.pk %}"><button  class = "btn btn-primary " type="submit" name="mark" >Schedule</button></a>
 	</li>



  <br>
{% endfor %}

		</ul>
	</div>


		</div>
	</div>

</body>
</html>

todolist/templates/todolist/schedule.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>TodoList App</title>
	<!-- bootstrap cdn -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- google fonts -->
	<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">	
</head>


  <body>
  		<div class="hero">
		<div class="container">
			<h3 class="display-2 text-center">Your Schedule</h3>
			
			<div class="row">
  			<div class="col-lg-12">
   			 {% for l in list %}



		  <h1>{{l.content}}</h1>
  		  Date:{{l.date}}
  		  <br>
  		  Time:{{l.time}}
  
{% endfor %}
</div>
</div>
</div>
</div>
</body>
</html>

todolist/templates/todolist/update.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>TodoList App</title>
	<!-- bootstrap cdn -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- google fonts -->
	<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">	
</head>


  <body>
  		
  	<div class="hero">
		<div class="container">
			<h3 class="display-2 text-center">TodoList</h3>
			<p class="lead text-center">Update Your Todo</p>
			<div class="row">
				<form id="form" class="col-lg-6 col-8 mx-auto" method="post">
					<div class="input-group">
						{% csrf_token %}
						{{form.as_p}}
						<span>
							<button id="btn" type="submit" class="btn btn-primary " style="font-size: 20px;">Submit</button>
						</span>
					</div>			     
				</form>
			</div>	
		</div>
	</div>		
</body>
</html>